title: The Hurricane Group
author:
  name: The Hurricane Group
  email: info@thehurricanegroup.com
description: > # this means to ignore newlines until "show_excerpts:"
  Providing the Windsor Region with unparalleled service in the sanitation and excavation industries.

show_excerpts: false # set to true to show excerpts on the homepage

logo: hurricane-group-logo.svg

sass:
  load_paths:
    - node_modules
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
exclude:
  - package.json
  - README.md
  - LICENSE.txt
  - yarn.lock
  
# Build settings
theme: hurricane-theme

plugins:
 - jekyll-seo-tag